###REGISTER
POST http://localhost:29052/auth/register
Content-Type: application/json


{
    "username": "jere1",
    "email": "jeretamargo02@gmail.com",
    "password": 123456
}

###LOGIN
POST http://localhost:29052/auth/login
Content-Type: application/json


{
    "username": "jere1",
    "password": 123456
}